version: '3.2'
services:
    webserver:
        networks:
            - traefik
        image: coronawhy/airflow-ts:v3.2
        #image: puckel/docker-airflow:1.10.9
        restart: always
        volumes:
            - ./dags:/usr/local/airflow/dags
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: /work/entrypoint.sh 
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.webserver.rule=Host(`${traefikhost}`)"
            - "traefik.http.routers.webserver.entrypoints=web"
  


networks:
  traefik:
    external: true
